[phases.setup]
nixPkgs = ["php82", "php82Extensions.gd", "php82Extensions.mbstring", "composer"]

[phases.install]
cmds = ["composer install --no-interaction --no-dev"]

[phases.build]
cmds = ["mkdir -p vendor"] # Подстраховка для создания директории

[start]
cmd = "php -S 0.0.0.0:$PORT"